# Creating a special Matrix that can cache its inverse and computing
# the inverse or retrieving the already computed one

# function used to create a special Matrix that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(z){
                x <<- z
                inv <<- NULL
        }
        get <- function() x
        setinv <- function(solve) inv <<- solve
        getinv <- function() inv
        list(set = set, get = get, setinv = setinv, getinv = getinv)

}


# function used to compute the inverse of the special Matrix
# generated by the "makeCacheMatrix" function and retrieve the
# inverse if it is already cached

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinv()
        if (!is.null(inv)){
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        inv <- solve(data, ...)
        x$setinv(inv)
        inv
}
